project:
  type: website
  output-dir: docs
website:

  title: "Meu site - Gustavo Barreto Giusti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true